.mdlrc, zwavejs2mqtt/DOCS.md
Extends the documentation with some more setup instruction on how to use the Z-Wave JS integration in Home Assistant with this add-on.
=> Extend setup instructions

zwavejs2mqtt/DOCS.md, zwavejs2mqtt/config.json, zwavejs2mqtt/rootfs/etc/cont-init.d/configuration.sh, zwavejs2mqtt/rootfs/etc/cont-init.d/folders.sh
Initiates a default configuration on the first run.
If the Mosquitto add-on is found, it will also fetch service information for that add-on and pre-configure that as well.
=> Initiate default configuration on first run

zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/discovery
This PR ensures the Discovery process waits for the Z-Wave JS process to become available.
The latest zwavejs2mqtt awaits for the driver to be ready before starting this process.
This means, we have to wait as well, or else the Home Assistant integration discovery flow will be silently aborted with an error.
Upstream commit: <https://github.com/zwave-js/zwavejs2mqtt/commit/8c7249e2bb17161132663a258e71aff4d0d04b64>
=> Ensure HA Discovery awaits for Z-Wave JS Server

zwavejs2mqtt/Dockerfile
zwavejs2mqtt is now 1.0.0
This upgrades the add-on to 1.0.1 and will now follow upstream releases.
- <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.0>
- <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.1>
=> Upgrade zwavejs2mqtt to v1.0.1

zwavejs2mqtt/config.json
`zwave-js-server` has an option to expose the port outside the host. This is useful for developing because I can connect a client locally while keeping my HA instance up.
=> Optionally expose WS port

zwavejs2mqtt/Dockerfile
Updates Z-Wave JS to MQTT to v1.1.0
Upstream release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.1.0>
=> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.1.0

zwavejs2mqtt/config.json
Enable the `udev` option on the add-on, so the control panel is capable of showing the serial devices by their alias paths (e.g., serial by-id paths).
=> Enable udev

zwavejs2mqtt/config.json
Could by maybe usefully take the add-on down if the software has an issue with the driver?
=> Allow Supervisor to use health check for watchdog

zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v2.0.0
Upstream release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.0.0>
=> ⬆️ Upgrades ZwaveJS2Mqtt to v2.0.0

zwavejs2mqtt/Dockerfile
<https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.0.1>
=> ⬆️ Upgrades ZwaveJS2Mqtt to v2.0.1

zwavejs2mqtt/Dockerfile
This PR is awaiting an upstream change/rectification of the release notes, as they contain information that is incorrect and untrue.
> It's since been worked out and was just a misunderstanding.
The add-on was removed because:
There was no misunderstanding in that.
CC @robertsLando @AlCalzone
Upstream release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.2.0>
=> ⬆️ Upgrades ZwaveJS2Mqtt to v3.2.0

zwavejs2mqtt/Dockerfile
Temporary bumps Z-Wave JS server to guarantee compatibility with Home Assistant 2021.9.0b0
=> ⬆️ Upgrades Z-Wave JS Server to 1.10.0

zwavejs2mqtt/Dockerfile
The builds of this add-on is often running towards network timeouts in yarn. This PR extends the timeout value to make it occur less often (and thus resulting in more consistent builds).
=> 🚑 Increase yarn network timeout for more consistent builds

zwavejs2mqtt/Dockerfile
The current version of this addon will not work with dev. It needs 5.7.3 at a minimum. This will also be the case in the next beta.
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.7.3
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.7.2
=> ⬆️ Upgrades ZwaveJS2Mqtt to v5.7.3

zwavejs2mqtt/Dockerfile
Update `zwavejs2mqtt` to 6.2.0. Motivated by zwavejs2mqtt 6.2.0 bumping `zwave-js` to 8.9.1. `zwave-js` 8.9.1 fixes a major bug (see links below). 
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.2.0
- https://github.com/zwave-js/zwavejs2mqtt/issues/2081
- https://community.home-assistant.io/t/all-controls-switches-shutters-etc-stop-working-after-a-while/362139/17
- https://community.home-assistant.io/t/z-wave-js-stopping-constantly/369395/38
=> ⬆️Update zwavejs2mqtt to 6.2.0

zwavejs2mqtt/rootfs/etc/nginx/templates/ingress.gtpl
Move "proxy_set_header X-External-Path" so that all proxy_set_header
options are defined at the same level. Fixes issue #51.
I've done some digging and believe I've found the cause issue #51:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
"These directives are inherited from the previous configuration level if and only if there are no proxy_set_header directives defined on the current level."
It looks like that is causing this line (https://github.com/hassio-addons/addon-zwavejs2mqtt/blob/main/zwavejs2mqtt/rootfs/etc/nginx/templates/ingress.gtpl#L12) to prevent any of the `proxy_set_header` config from `include /etc/nginx/includes/proxy_params.conf;` from taking effect. Specifically, the two lines:
```
proxy_set_header Connection $connection_upgrade; …
```
=> Fix upgrading firmware from Ingress

zwavejs2mqtt/Dockerfile
Update zwavejs2mqtt from 6.5.0 to 6.5.1
Updates zwavejs2mqtt from 6.5.0 to 6.5.1, only minor difference
> (Describe the changes and rationale behind them)
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.5.1
=> ⬆️ Upgrades ZwaveJS2Mqtt to v6.5.1

zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/run
Forcibly disables SSL for this add-on, which should address issues like #309 
There is no valid reason to enable/handle SSL inside the add-on itself on this platform, as SSL termination is handled elsewhere.
=> Force disable SSL

zwave-js-ui/Dockerfile, zwave-js-ui/build.yaml
Updates the add-on base image to a new major version, based on Alpine Linux 3.17 and NodeJS 18
=> ⬆️ Upgrades add-on base image to 13.0.0

README.md
Remove a duplicate instance of the line `This add-on uses the Z-Wave JS UI software.`
N/A
=> Remove duplicate reference to Zwave js ui

zwave-js-ui/Dockerfile
Bumps python3-dev to 3.10.10-r0 and nodejs to 18.14.1-r0 due to Alpine 3.17 updates.
* https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.17
* https://pkgs.alpinelinux.org/packages?name=python3-dev&branch=v3.17
> #467
=> Bump python3-dev=3.10.10-r0, nodejs=18.14.1-r0

zwave-js-ui/rootfs/etc/s6-overlay/s6-rc.d/zwave-js-ui/run
Cleans up an old leftover, which causes a warning to be shown during startup. Never noticed, as zwavejs itself spam the log full pretty quick :)
=> :broom: Clean up left over from old discovery

zwave-js-ui/Dockerfile, zwave-js-ui/build.yaml
Attempt to fix the CI/build issues we are experiencing, but switching to a custom base image that is based on Alpine Linux 3.19 and NodeJS v18
=> Switch to custom NodeJS base image
