- zwavejs2mqtt/Dockerfile
Upgrade the database to the latest greatest.
> Upgrade Z-Wave JS database to 93d505e97daa7649d0d4af16d0145b52cbdcc141

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.2
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.2

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
> Upgrade add-on base image to 9.1.2

- zwavejs2mqtt/Dockerfile
<https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.3>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.3

- zwavejs2mqtt/Dockerfile
> :arrow_up: Update OpenZWave database to 76408b1623f966815c98a4b5ce581

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.4
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.0.5
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.0.5

- .github/workflows/ci.yaml
- zwavejs2mqtt/config.json
Make add-on configuration compatible with Supervisor 2021.2 or newer.
> Update add-on configuration for Supervisor 2021.2

- zwavejs2mqtt/Dockerfile
Updates device database to the latest commits.
> Update database to d86e9956f6b0160fcf675c2b3d33faed33dfba7c

- zwavejs2mqtt/Dockerfile
> Update database to 6cc6466e2ce050b95364b1740cc6d123af3cdba1

- zwavejs2mqtt/Dockerfile
Release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.1.1>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.1.1

- zwavejs2mqtt/Dockerfile
> :arrow_up: Upgrades nodejs to 14.15.5-r0

- zwavejs2mqtt/Dockerfile
> :arrow_up: Upgrades libusb to 1.0.24-r1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrade add-on base image to 9.1.3
> Upgrade add-on base image to 9.1.3

- zwavejs2mqtt/Dockerfile
Upstream changes:
<https://github.com/zwave-js/zwavejs2mqtt/compare/v1.1.1...v1.2.0>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.0

- zwavejs2mqtt/Dockerfile
> Update database to bcb1feca586b2fe1dc584283e548e1441d188547

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.2.1
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.1

- zwavejs2mqtt/Dockerfile
Upgrades python3-dev to 3.8.7-r1
> :arrow_up: Upgrades python3-dev to 3.8.7-r1

- zwavejs2mqtt/Dockerfile
<https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.2.2>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.2

- zwavejs2mqtt/config.json
Fixes the URL in a format that the Supervisor expects.
> Fix Watchdog URL to match Supervisor validation

- zwavejs2mqtt/Dockerfile
Upstream release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.2.3>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v1.2.3

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.16.0-r0

- zwavejs2mqtt/Dockerfile
Update database to 23f96601431beb6c8b2bf88b6dcc580612d0fcd3
> Update database to 23f96601431beb6c8b2bf88b6dcc580612d0fcd3

- zwavejs2mqtt/Dockerfile
> Update database to 37f4b05431d5513cda291560a31de3a951c17f11

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
> :arrow_up: Upgrades add-on base image to v9.1.5

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.1.0
> :arrow_up: Upgrades ZwaveJS2Mqtt to v2.1.0

- zwavejs2mqtt/Dockerfile
> Update database to 3c9ea7190f4f704070bbffedf9a03df647b73221

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.1.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v2.1.1

- zwavejs2mqtt/Dockerfile
Release notes: <https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.1.2>
> :arrow_up: Upgrades ZwaveJS2Mqtt to v2.1.2

- zwavejs2mqtt/Dockerfile
> Update database to 1f800c77d1406eef3f6298ff3d4134c87baa66b6

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.2.0
> :arrow_up: Upgrades ZwaveJS2Mqtt to v2.2.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.3.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v2.3.0

- zwavejs2mqtt/Dockerfile
Update database to d4d6c1dcf239359ec52b9482465d9d3e8d2ad984
> Update database to d4d6c1dcf239359ec52b9482465d9d3e8d2ad984

- zwavejs2mqtt/Dockerfile
Upgrades python3-dev to 3.8.8-r0
> ⬆️ Upgrades python3-dev to 3.8.8-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.4.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v2.4.0

- zwavejs2mqtt/Dockerfile
> Update database to 840fdd7d81ba6b94dae36c006da450476554822d

- zwavejs2mqtt/Dockerfile
> Update database to ff8e4088321dc6490efde18a31ec893939de4de7

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.4.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v2.4.1

- zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v3.0.0
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.0.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.0.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.0.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.0.1

- zwavejs2mqtt/Dockerfile
> Update database to 6f8ebe0226414100b0969a36888e46bb1f7fa987

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.0.3
https://github.com/zwave-js/zwavejs2mqtt/compare/v3.0.1...v3.0.3
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.0.3

- zwavejs2mqtt/Dockerfile
Update database to bb6012deb9e0d99e3a0f3f6d1efbea28f4766a31
> Update database to bb6012deb9e0d99e3a0f3f6d1efbea28f4766a31

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.1.0

- zwavejs2mqtt/Dockerfile
> Update database to 68294d7406bf6603b058ffeab1c1dc4949a5a7d3

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.16.1-r0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to v9.1.7
> ⬆️ Upgrades add-on base image to v9.1.7

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.2.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.2.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.16.1-r1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.3.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.3.0

- zwavejs2mqtt/Dockerfile
> Update database to 36535100be7530c17473214c221bce49ba01842f

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to v9.1.8
> ⬆️ Upgrades add-on base image to v9.1.8

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.4.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.4.0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to v9.2.0
> Upgrades add-on base image to v9.2.0

- zwavejs2mqtt/translations/en.yaml
Add translation support for the add-on options.
> Add add-on translation support

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.5.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v3.5.0

- zwavejs2mqtt/Dockerfile
> (Describe the changes and rationale behind them)
> Update database to 9a965250d23687a2348b97288c67699169b66545

- zwavejs2mqtt/Dockerfile
Update database to 060eba16cecf4f5f6eb0a75e2bdbde27a4986e1c
> Update database to 060eba16cecf4f5f6eb0a75e2bdbde27a4986e1c

- zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v4.0.0
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.0.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.0.0

- zwavejs2mqtt/Dockerfile
> Fix hanging config update

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.0.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.0.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/rootfs/etc/cont-init.d/configuration.sh
- zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/run
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.2.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.2.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.2.1

- zwavejs2mqtt/Dockerfile
This PR cleans up the download of the latest database, as that is no longer needed.
> Clean up download of latest DB

- zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v4.3.0
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.3.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.3.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.3.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.3.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.4.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.4.0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to v9.2.1
> ⬆️  Upgrades add-on base image to v9.2.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.5.0
> ⬆️  Upgrades ZwaveJS2Mqtt to v4.5.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.5.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v4.5.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to v9.2.2
> ⬆️ Upgrades add-on base image to v9.2.2

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.5.2
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.0.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.0.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.0.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/run
- Updates build to use `yarn`.
- Adjusts service script to use new server location.
> Update build and service scripts to match upstream changes

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.0.2
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.0.2

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades the base image of the add-on to v10.0.0
<https://github.com/hassio-addons/addon-base/releases/tag/v10.0.0>
> ⬆️ Upgrades add-on base image to v10.0.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.0.4
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.0.4

- zwavejs2mqtt/Dockerfile
<https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.1.0>
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.1.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.2.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.2.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.2.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.2.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.2.2
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.2.2

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.3.0
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.4.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.4.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.2
fixes #222
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.4.2

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.17.4-r0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v10.0.1
> ⬆️ Upgrades add-on base image to v10.0.1

- zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v5.4.5
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.3
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.4
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.5
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.4.5

- zwavejs2mqtt/rootfs/etc/nginx/includes/ssl_params.conf
Updates the SSL parameters of NGINX to the latest intermediate level by Mozilla
> 🔑 Update NGINX SSL parameters

- zwavejs2mqtt/config.json
> 🏎 Enable streaming mode for Ingress

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.4.6
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.4.6

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.5.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.5.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.5.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.5.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.17.6-r0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.json
Upgrades add-on base image to 10.1.0
> ⬆️ Upgrades add-on base image to 10.1.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.0
> Upgrades ZwaveJS2Mqtt to v5.6.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.6.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.2
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.6.2

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.7.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.7.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.7.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.7.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 14.18.1-r0

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.9.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.10.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.10.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.10.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 10.2.1
> ⬆️ Upgrades add-on base image to 10.2.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.11.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.11.0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 10.2.2
> ⬆️ Upgrades add-on base image to 10.2.2

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nginx to 1.20.2-r0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 10.2.3
> ⬆️ Upgrades add-on base image to 10.2.3

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.12.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v5.12.0

- zwavejs2mqtt/Dockerfile
Upgrades python3-dev to 3.9.5-r2
> ⬆️ Upgrades python3-dev to 3.9.5-r2

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.0.0
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.0.1
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.0.2
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.0.2

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 11.0.0
> ⬆️ Upgrades add-on base image to 11.0.0

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 16.13.1-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.0.3
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.0.3

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.1.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.1.0

- zwavejs2mqtt/config.yaml
Allowing the add-on to be found on `Zwavejs2Mqtt`.
CC @blhoward2
> Improve search-ability on Zwavejs2Mqtt

- zwavejs2mqtt/Dockerfile
Upgrades ZwaveJS2Mqtt to v6.1.1
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.1.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.1.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 11.0.1
> ⬆️ Upgrades add-on base image to 11.0.1

- LICENSE.md
- README.md
- zwavejs2mqtt/.README.j2
- zwavejs2mqtt/DOCS.md
Updates maintenance/license year to 2022
> :fireworks: Updates maintenance/license year to 2022

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.3.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.3.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.3.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.3.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 16.13.2-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.4.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.4.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.4.1
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.4.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.5.0
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.5.0

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 16.14.0-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.5.2
> ⬆️ Upgrades ZwaveJS2Mqtt to v6.5.2

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 11.1.0
> ⬆️ Upgrades add-on base image to 11.1.0

- .github/workflows/deploy.yaml
- zwavejs2mqtt/build.yaml
- zwavejs2mqtt/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- README.md
- zwavejs2mqtt/.README.j2
- zwavejs2mqtt/DOCS.md
Adds my buttons and a note to the introduction.
> :books: Add My buttons to documentation

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 11.1.1
> ⬆️ Upgrades add-on base image to 11.1.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.6.0
> ⬆️ Upgrades zwavejs2mqtt to v6.6.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.6.1
> ⬆️ Upgrades zwavejs2mqtt to v6.6.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 16.14.2-r0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 11.1.2
> ⬆️ Upgrades add-on base image to 11.1.2

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nginx to 1.20.2-r1

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.7.3
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.7.4
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.8.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.8.1
> ⬆️ Upgrades zwavejs2mqtt to v6.8.1

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.9.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.9.1
> ⬆️ Upgrades zwavejs2mqtt to v6.9.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.10.0
> ⬆️ Upgrades zwavejs2mqtt to v6.10.0

- zwavejs2mqtt/Dockerfile
<https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.11.0>
> ⬆️ Upgrades zwavejs2mqtt to v6.11.0

- zwavejs2mqtt/DOCS.md
> :books: Use new My Home Assistant link format

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Updates the add-on base image to 12.2.0
> ⬆️ Upgrades add-on base image to 12.2.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.12.1
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.13.0
> Update zwavejs2mqtt to 6.13.0

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nginx to 1.22.0-r1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 12.2.1
> ⬆️ Upgrades add-on base image to 12.2.1

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades nodejs to 16.16.0-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.14.0
> ⬆️ Upgrades zwavejs2mqtt to v6.14.0

- zwavejs2mqtt/Dockerfile
> ⬆️ Upgrades python3-dev to 3.10.5-r0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.14.1
> ⬆️ Upgrades zwavejs2mqtt to v6.14.1

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.2

- zwavejs2mqtt/Dockerfile
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.15.0
- https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.15.1
> ⬆️ Upgrades zwavejs2mqtt to v6.15.1

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.15.2
> ⬆️ Upgrades zwavejs2mqtt to v6.15.2

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
Upgrades add-on base image to 12.2.3
> ⬆️ Upgrades add-on base image to 12.2.3

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v7.0.0
https://github.com/zwave-js/node-zwave-js/issues/4994
> ⬆️ Upgrades zwavejs2mqtt to v7.0.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v7.0.0
> ⬆️ Upgrades zwavejs2mqtt to 7.0.0

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v7.1.0
> Upgrades zwavejs2mqtt to 7.1.0

- zwavejs2mqtt/Dockerfile
- zwavejs2mqtt/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.4

- zwavejs2mqtt/Dockerfile
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v7.2.0
> ⬆️ Upgrades zwavejs2mqtt to v7.2.0

- zwavejs2mqtt/DOCS.md
Update the Home Assistant integration setup steps to reflect recent frontend changes in HA.
- Configuration was renamed to Settings
- Integrations was renamed to Devices & Services
- Z-Wave JS integration was renamed to Z-Wave
N/A
> Update Home Assistant instructions

- README.md
- zwave-js-ui/.README.j2
After 80 releases, I think we can safely mark the add-on as stable.
> Mark project as production ready

- zwave-js-ui/.README.j2
> Fix broken link in add-on readme

- zwave-js-ui/Dockerfile
Changelog: https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.0.1
> ⬆️ Upgrades Z-Wave JS UI to v8.0.1

- zwave-js-ui/Dockerfile
Changelog:
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.1.0
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.0.2
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.0.3
> ⬆️ Upgrades Z-Wave JS UI to v8.1.0

- zwave-js-ui/Dockerfile
> ⬆️ Upgrades nodejs to 16.17.1-r0

- zwave-js-ui/Dockerfile
> ⬆️ Upgrades nginx to 1.22.1-r0

- zwave-js-ui/Dockerfile
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.2.0
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.2.1
> ⬆️ Upgrades Z-Wave JS UI to v8.2.1

- zwave-js-ui/Dockerfile
Upgrades Z-Wave JS UI to v8.2.2
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.2.2
> ⬆️ Upgrades Z-Wave JS UI to v8.2.2

- zwave-js-ui/Dockerfile
- zwave-js-ui/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.6

- zwave-js-ui/Dockerfile
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.4.1
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.4.0
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.3.0
> ⬆️ Upgrades Z-Wave JS UI to v8.4.1

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.5.0
> ⬆️ Upgrades Z-Wave JS UI to v8.5.0

- zwave-js-ui/Dockerfile
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.5.1
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.6.0
> ⬆️ Upgrades Z-Wave JS UI to v8.6.0

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.6.1
> ⬆️ Upgrades Z-Wave JS UI to v8.6.1

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.6.2
> ⬆️ Upgrades Z-Wave JS UI to v8.6.2

- zwave-js-ui/Dockerfile
- zwave-js-ui/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.0

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.7.0
> ⬆️ Upgrades Z-Wave JS UI to v8.7.0

- LICENSE.md
- README.md
- zwave-js-ui/.README.j2
- zwave-js-ui/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- zwave-js-ui/Dockerfile
- zwave-js-ui/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.1

- zwave-js-ui/Dockerfile
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.2
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.1
> ⬆️ Upgrades Z-Wave JS UI to v8.8.2

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.3
> ⬆️ Upgrades Z-Wave JS UI to v8.8.3

- zwave-js-ui/Dockerfile
Upgrades Z-Wave JS UI to v8.8.5
* https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.4
* https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.5
* https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.6
> [#463 ](https://github.com/hassio-addons/addon-zwave-js-ui/pull/463)
> ⬆️ Upgrades Z-Wave JS UI to v8.8.6

- zwave-js-ui/Dockerfile
- zwave-js-ui/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.3

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.9.0
> ⬆️ Upgrades Z-Wave JS UI to v8.9.0

- zwave-js-ui/.README.j2
correct small typo to "decoupled"
> (Describe the changes and rationale behind them)
> Fix typo in README

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.10.0
> ⬆️ Upgrades Z-Wave JS UI to v8.10.0

- zwave-js-ui/Dockerfile
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.10.1
> ⬆️ Upgrades Z-Wave JS UI to v8.10.1

- .github/dependabot.yaml
- .github/renovate.json
- zwave-js-ui/Dockerfile
Adds Renovate for Dependency management
> Add Renovate for dependency management

- zwave-js-ui/DOCS.md
> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> Fix broken URL

- zwave-js-ui/Dockerfile
- zwave-js-ui/config.yaml
- zwave-js-ui/rootfs/etc/nginx/templates/ingress.gtpl
> Replace watchdog with Docker health check

- README.md
- zwave-js-ui/build.yaml
- zwave-js-ui/config.yaml
> Drop support for armhf & i386

- zwave-js-ui/Dockerfile
> Migrate yarn to npm

- LICENSE.md
- README.md
- zwave-js-ui/.README.j2
- zwave-js-ui/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- LICENSE.md
- README.md
- zwave-js-ui/.README.j2
- zwave-js-ui/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
